CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    full_name VARCHAR(255),
    place_of_birth VARCHAR(255),
    date_of_birth DATE,
    citizenship VARCHAR(100),
    gender VARCHAR(10),
    number_of_children INT,
    marital_status VARCHAR(50),
    occupation VARCHAR(255),
    customer_registration_date DATE,
    monthly_income DECIMAL(15,2),
    education_level VARCHAR(100),
    city VARCHAR(100),
    number_of_loans INT
);

CREATE TABLE credit_scores (
    customer_id INT,
    credit_score INT,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE customer_loans (
    document_id INT PRIMARY KEY,
    customer_id INT,
    product_type VARCHAR(100),
    loan_type VARCHAR(100),
    currency_type VARCHAR(10),
    loan_start_date DATE,
    loan_end_date DATE,
    loan_status VARCHAR(50),
    requested_amount DECIMAL(15,2),
    approved_amount DECIMAL(15,2),
    principal_debt DECIMAL(15,2),
    total_debt DECIMAL(15,2),
    secondary_purpose_code VARCHAR(50),
    secondary_purpose_description VARCHAR(255),
    tertiary_purpose_code VARCHAR(50),
    tertiary_purpose_description VARCHAR(255),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE surveys (
    customer_id INT,
    country_of_residence VARCHAR(100),
    citizenship VARCHAR(100),
    is_politician BOOLEAN,
    has_political_affiliation BOOLEAN,
    account_purpose VARCHAR(255),
    annual_account_activity_range VARCHAR(50),
    current_account_local_currency_balance DECIMAL(15,2),
    number_of_current_accounts INT,
    savings_account_local_currency_balance DECIMAL(15,2),
    number_of_savings_accounts INT,
    investment_account_local_currency_balance DECIMAL(15,2),
    number_of_investment_accounts INT,
    authorized_signatory_country_of_residence VARCHAR(100),
    authorized_signatory_citizenship VARCHAR(100),
    company_partner_citizenship VARCHAR(100),
    number_of_family_members INT,
    gender VARCHAR(10),
    marital_status VARCHAR(50),
    education_level VARCHAR(100),
    occupation VARCHAR(255),
    age INT,
    additional_income DECIMAL(15,2),
    has_collateral BOOLEAN,
    owns_valuable_items BOOLEAN,
    owns_real_estate BOOLEAN,
    loan_purpose VARCHAR(255),
    loan_branch VARCHAR(100),
    number_of_loans INT,
    loan_month VARCHAR(50),
    primary_income_percentage DECIMAL(5,2),
    income_type VARCHAR(100),
    expense_to_income_ratio DECIMAL(5,2),
    negative_comment_from_loan_department BOOLEAN,
    years_of_employment INT,
    years_in_same_residence INT,
    job_position VARCHAR(255),
    movable_property_value_in_usd DECIMAL(15,2),
    immovable_property_value_land_in_usd DECIMAL(15,2),
    second_property_value_in_usd DECIMAL(15,2),
    immovable_property_value_house_in_usd DECIMAL(15,2),
    is_customer_on_banned_list BOOLEAN,
    is_regular_customer BOOLEAN,
    total_score INT,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);
